### PR TITLE
moved ROS Graph api to new module

### PR DESCRIPTION
**Pull request by hsd-dev**

### CODE REVIEW

**Comment by hsd-dev** [comment]
https://github.com/ipa320/rosgraph_monitor/pull/10/commits/f35260551583ff779b539f1053e7a4fbfb2e3a7e is temp commit.

**Comment by hsd-dev** [comment]
@ipa-nhg

**Comment by NadiaHG** [comment]
requires: https://github.com/ipa320/ros_model_parser/pull/19

**Review by ipa-nhg — APPROVED** [review]
LGTM! Tested and it works!

**Pull request merged**
