### PR TITLE
Add CI configuration

### LINKED ISSUE #2: Add CI configuration for this repository
Add to a new file under `.github/workflows/build.yml` the content:

```
name: CI
on: [push, pull_request]
jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic}
          - {ROS_DISTRO: noetic}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
```

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by NadiaHG** [comment]
The configuration is ready https://github.com/ipa-nhg/rosgraph_monitor/actions/runs/793039786 , this requires the changes from the PR #1

**Comment by hsd-dev** [comment]
This looks good! Thanks for this! :100:

**Review by hsd-dev — APPROVED** [review]

**Comment by NadiaHG** [comment]
@ipa-hsd you can decide if you want to merge this before or after the #1 , very likely there will be a merge conflict, ping me if you need help to solve it.

**Comment by hsd-dev** [comment]
Closing this in favour of https://github.com/ipa320/rosgraph_monitor/pull/5

**Pull request closed without merging**
